### ISSUE TITLE
Comparison to Residual Connections?

### ISSUE THREAD

**Issue by kuza55** [frederick0329/Handling-Homographs#1]
Hi,

Apologies if I got something really confused, but the "BiLSTM Context Network" seemed similar to a 3 layer LSTM with a residual connection from the word embeddings to the 2nd LSTM layer.

Eventually I realised that this work is different because you use concatenation, rather than addition, but I think it would be interesting to compare your approach to methods such as residual/highway connections to see how concatenation fits into the general approaches to skip connections for NMT.

**Comment by frederick0329** [comment]
Great question. 
The default implementation of bidirectional multi-layer LSTMs in OpenNMT aggregates information from both direction in the last layer. On the other hand, our BiLSTM Context Network aggregates information in the first layer.
Regarding residual experiments, the last paragraph on page6 shows some results.
